project:
  type: book
  pre-render:
    - scripts/check_packages.R
  execute-dir: project

book:
  title: "Practical Data Analysis in Sociology Using R"
  author: "Aaron Gullickson"
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - chapters/understanding_workflow.qmd
        - chapters/using_git.qmd
        - chapters/learning_r.qmd
    - part: "The Tidyverse"
      chapters: 
        - chapters/becoming_tidyversant.qmd
        - chapters/making_pictures.qmd
        - chapters/writing_quarto.qmd
    - part: "Data Wrangling"
      chapters:
        - chapters/reading_data.qmd
        - chapters/subsetting_data.qmd
        - chapters/recoding_variables.qmd
        - chapters/reshaping_data.qmd
        - chapters/merging_data.qmd
    - part: "Programmming"
      chapters:
        - chapters/creating_functions.qmd
        - chapters/iterating_speed.qmd
  appendices:
        - appendices/getting_familiar_rstudio.qmd


bibliography: bibliography/references.bib

format:
  html:
    theme: darkly
    css: styles.css
    html-table-processing: none
execute:
  freeze: auto
  warning: false
  message: false
number-depth: 1

